services:
  postgres:
    build:
      context: './server'
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=calcpostgres
      - POSTGRES_DB=postgres
  mongo:
    image: 'mongo'
    ports:
      - 27062:27017